import Providers from '@/redux/provider'
import '@/fonts/fonts.css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/layouts/header/Header'
import ToastProvider from '@/components/toastProvider/ToastProvider'
import Footer from '@/layouts/footer/Footer'
import NavbarProvider from '@/layouts/navbar/NavbarProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <ToastProvider />
          <NavbarProvider>
            {children}
          </NavbarProvider>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
